### PR TITLE
fix: accessibility fixes for demo app

### PR DESCRIPTION
**Pull request by Charlotteis**
Hi! I didn't get a chance to review the changes made to the demo app before it was merged so I have a few additions if that's okay.

I've moved the header out of the label and made it stand on its own, I've added a more descriptive label to the input. I've also made it more explicit what we're checking and clearing. Lastly, just from a code cleanliness perspective, I moved the inline-style on the `js-todo-container` to the style.css file.

@ShellyCoen I'd really like to know your thoughts, hope these additions are ok?

👻

### CODE REVIEW

**Comment by nickcolley** [comment]
Looks good to me. :+1:

**Comment by Charlotteis** [comment]
Thanks @ShellyCoen :)

**Comment by ShellyCoen** [comment]
No, thank YOU! I would have merged it yesterday evening but I had internet issues :)  
  
Also, fun story, this was my first time to merge a PR on the comment line, so thanks for that also :P

**Comment by Charlotteis** [comment]
I've never merged a PR from the command line!

**Pull request merged**
